### ISSUE TITLE
which paper is this repo corresponding to?

### ISSUE THREAD

**Issue by AOOOOOA** [rjunderwood/AV-Tester#3]
Hi, thanks for open-sourcing your code. I'm curious about which paper the repo is for. Could you give me the title so that I can better understand the code.

**Comment by AOOOOOA** [comment]
So sorry I missed the pdf file in the repo. But maybe you can add the title to the README if you have time. Anyway, thanks again.

**Comment by rjunderwood** [comment]
Added the paper url to README
